name = "m_beklemishev"
version = "0.1.0"
defaultTargets = ["m_beklemishev"]

[[lean_lib]]
name = "MBeklemishev"

[[lean_exe]]
name = "m_beklemishev"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"